-- CreateTable
CREATE TABLE "Question" (
    "ID_QT" TEXT NOT NULL,
    "TITLE" VARCHAR(60) NOT NULL,
    "DESCRIPTION" VARCHAR(255) NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "ID_USER" TEXT NOT NULL,
    "ID_CT" TEXT NOT NULL,

    CONSTRAINT "Question_pkey" PRIMARY KEY ("ID_QT")
);

-- AddForeignKey
ALTER TABLE "Question" ADD CONSTRAINT "Question_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Question" ADD CONSTRAINT "Question_ID_CT_fkey" FOREIGN KEY ("ID_CT") REFERENCES "CATEGORIES"("ID_CT") ON DELETE RESTRICT ON UPDATE CASCADE;
