-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

-- CreateTable
CREATE TABLE "USER" (
    "ID_USER" TEXT NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "ROLE" "UserRole" NOT NULL DEFAULT 'USER',
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("ID_USER")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_USERNAME_key" ON "USER"("USERNAME");

-- CreateIndex
CREATE UNIQUE INDEX "USER_EMAIL_key" ON "USER"("EMAIL");
