version: '3.8'

services:
  backend:
    build: .
    container_name: backend-forum
    restart: always
    command: npm run start:prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - shared-net
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: tauan
      POSTGRES_PASSWORD: tauan2143
      POSTGRES_DB: forum
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-net

volumes:
  postgres_data:

networks:
  shared-net:
    external: true
