-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

-- CreateEnum
CREATE TYPE "TypeVotes" AS ENUM ('LIKE', 'DESLIKE');

-- CreateTable
CREATE TABLE "USERS" (
    "ID_USER" TEXT NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "ROLE" "UserRole" NOT NULL DEFAULT 'USER',
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID_USER")
);

-- CreateTable
CREATE TABLE "CATEGORIES" (
    "ID_CT" TEXT NOT NULL,
    "CATEGORY" VARCHAR(45) NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),

    CONSTRAINT "CATEGORIES_pkey" PRIMARY KEY ("ID_CT")
);

-- CreateTable
CREATE TABLE "QUESTIONS" (
    "ID_QT" TEXT NOT NULL,
    "TITLE" VARCHAR(60) NOT NULL,
    "DESCRIPTION" TEXT NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),
    "ID_USER" TEXT NOT NULL,
    "ID_CT" TEXT NOT NULL,

    CONSTRAINT "QUESTIONS_pkey" PRIMARY KEY ("ID_QT")
);

-- CreateTable
CREATE TABLE "ANSWERS" (
    "ID_AN" TEXT NOT NULL,
    "RESPONSE" TEXT NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),
    "ID_USER" TEXT NOT NULL,
    "ID_QT" TEXT NOT NULL,

    CONSTRAINT "ANSWERS_pkey" PRIMARY KEY ("ID_AN")
);

-- CreateTable
CREATE TABLE "VOTES" (
    "ID_VT" TEXT NOT NULL,
    "TYPE" "TypeVotes" NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "ID_USER" TEXT NOT NULL,
    "ID_AN" TEXT NOT NULL,

    CONSTRAINT "VOTES_pkey" PRIMARY KEY ("ID_VT")
);

-- CreateIndex
CREATE UNIQUE INDEX "VOTES_ID_USER_ID_AN_key" ON "VOTES"("ID_USER", "ID_AN");

-- AddForeignKey
ALTER TABLE "QUESTIONS" ADD CONSTRAINT "QUESTIONS_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QUESTIONS" ADD CONSTRAINT "QUESTIONS_ID_CT_fkey" FOREIGN KEY ("ID_CT") REFERENCES "CATEGORIES"("ID_CT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ANSWERS" ADD CONSTRAINT "ANSWERS_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ANSWERS" ADD CONSTRAINT "ANSWERS_ID_QT_fkey" FOREIGN KEY ("ID_QT") REFERENCES "QUESTIONS"("ID_QT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VOTES" ADD CONSTRAINT "VOTES_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VOTES" ADD CONSTRAINT "VOTES_ID_AN_fkey" FOREIGN KEY ("ID_AN") REFERENCES "ANSWERS"("ID_AN") ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE UNIQUE INDEX unique_username_active
ON "USERS" ("USERNAME")
WHERE "DEL_AT" IS NULL;

CREATE UNIQUE INDEX unique_email_active
ON "USERS" ("EMAIL")
WHERE "DEL_AT" IS NULL;
