-- CreateTable
CREATE TABLE "CATEGORIES" (
    "ID_CT" TEXT NOT NULL,
    "CATEGORY" VARCHAR(45) NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CATEGORIES_pkey" PRIMARY KEY ("ID_CT")
);
