/*
  Warnings:

  - You are about to drop the `Question` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "public"."Question" DROP CONSTRAINT "Question_ID_CT_fkey";

-- DropForeignKey
ALTER TABLE "public"."Question" DROP CONSTRAINT "Question_ID_USER_fkey";

-- DropTable
DROP TABLE "public"."Question";

-- CreateTable
CREATE TABLE "QUESTIONS" (
    "ID_QT" TEXT NOT NULL,
    "TITLE" VARCHAR(60) NOT NULL,
    "DESCRIPTION" VARCHAR(255) NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),
    "ID_USER" TEXT NOT NULL,
    "ID_CT" TEXT NOT NULL,

    CONSTRAINT "QUESTIONS_pkey" PRIMARY KEY ("ID_QT")
);

-- CreateTable
CREATE TABLE "ANSWERS" (
    "ID_AN" TEXT NOT NULL,
    "RESPONSE" TEXT NOT NULL,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "DEL_AT" TIMESTAMP(3),
    "ID_USER" TEXT NOT NULL,
    "ID_QT" TEXT NOT NULL,

    CONSTRAINT "ANSWERS_pkey" PRIMARY KEY ("ID_AN")
);

-- AddForeignKey
ALTER TABLE "QUESTIONS" ADD CONSTRAINT "QUESTIONS_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QUESTIONS" ADD CONSTRAINT "QUESTIONS_ID_CT_fkey" FOREIGN KEY ("ID_CT") REFERENCES "CATEGORIES"("ID_CT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ANSWERS" ADD CONSTRAINT "ANSWERS_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ANSWERS" ADD CONSTRAINT "ANSWERS_ID_QT_fkey" FOREIGN KEY ("ID_QT") REFERENCES "QUESTIONS"("ID_QT") ON DELETE RESTRICT ON UPDATE CASCADE;
