-- CreateTable
CREATE TABLE "TokenReset" (
    "ID_TOKEN" TEXT NOT NULL,
    "TOKEN" TEXT NOT NULL,
    "EXPIRATION" TIMESTAMP(3) NOT NULL,
    "USED" BOOLEAN NOT NULL DEFAULT false,
    "ID_USER" TEXT NOT NULL,

    CONSTRAINT "TokenReset_pkey" PRIMARY KEY ("ID_TOKEN")
);

-- AddForeignKey
ALTER TABLE "TokenReset" ADD CONSTRAINT "TokenReset_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;
