/*
  Warnings:

  - You are about to drop the column `VOTES` on the `ANSWERS` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "ANSWERS" DROP COLUMN "VOTES";

-- CreateTable
CREATE TABLE "VOTES" (
    "ID_VT" TEXT NOT NULL,
    "VOTES" INTEGER NOT NULL DEFAULT 0,
    "DT_CR" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DT_UP" TIMESTAMP(3) NOT NULL,
    "ID_USER" TEXT NOT NULL,
    "ID_AN" TEXT NOT NULL,

    CONSTRAINT "VOTES_pkey" PRIMARY KEY ("ID_VT")
);

-- CreateIndex
CREATE UNIQUE INDEX "VOTES_ID_USER_ID_AN_key" ON "VOTES"("ID_USER", "ID_AN");

-- AddForeignKey
ALTER TABLE "VOTES" ADD CONSTRAINT "VOTES_ID_USER_fkey" FOREIGN KEY ("ID_USER") REFERENCES "USERS"("ID_USER") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "VOTES" ADD CONSTRAINT "VOTES_ID_AN_fkey" FOREIGN KEY ("ID_AN") REFERENCES "ANSWERS"("ID_AN") ON DELETE RESTRICT ON UPDATE CASCADE;
